[fleet]
control-node ansible_connection=local ansible_host=127.0.0.1
fleet-node-1 ansible_host=192.168.252.3 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/fleet_lab_ed25519

[fleet:vars]
ansible_python_interpreter=/usr/bin/python3
